services:
  - type: web
    name: wildfiresweb
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://wildfires-web.vercel.app,https://wildfiresweb.onrender.com,http://localhost:3000
      - key: FIRMS_API_KEY
        sync: false
        value: ddd2b8a0e248043cd289a751d54304cf
      - key: PYTHONPATH
        value: /app
    healthCheckPath: /health
    plan: free
